# Generated by Django 5.1.4 on 2024-12-16 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_question_description_alter_quiz_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='description',
            new_name='instruction',
        ),
    ]
