# Generated by Django 5.1.4 on 2024-12-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_rename_description_question_instruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
